### ISSUE TITLE
在mac机器上，make失败

### ISSUE THREAD

**Issue by luckypoem** [hchen90/vssocks#1]
yudeMacBook-Air:vssocks brite$ make
Scanning dependencies of target hdrs
[  0%] Built target hdrs
Scanning dependencies of target vssocks
[  5%] Building CXX object src/CMakeFiles/vssocks.dir/buffer.cpp.o
[ 11%] Building CXX object src/CMakeFiles/vssocks.dir/client.cpp.o
[ 16%] Building CXX object src/CMakeFiles/vssocks.dir/conf.cpp.o
[ 22%] Building CXX object src/CMakeFiles/vssocks.dir/crypto.cpp.o
[ 27%] Building CXX object src/CMakeFiles/vssocks.dir/peer.cpp.o
/Users/brite/vssocks/src/peer.cpp:89:41: error: use of undeclared identifier
      'MSG_NOSIGNAL'
      server_srv.setsockopt(SOL_SOCKET, MSG_NOSIGNAL, &num, sizeof(num));
                                        ^
1 error generated.
make[2]: *** [src/CMakeFiles/vssocks.dir/peer.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/vssocks.dir/all] Error 2
make: *** [all] Error 2
yudeMacBook-Air:vssocks brite$

如何解决？

**Comment by hchen90** [comment]
pull最近代码

> brew 安装一下 openssl 和 libev 的依赖库

**Comment by luckypoem** [comment]
hi.

现在，在Mac上make成功，不过没有看明白配置文件https://github.com/hchen90/vssocks/blob/master/sample.conf ,
没有看明白pat的值和local的值，眼睛都看花了，能解释一下这2个值的结构吗

**Comment by hchen90** [comment]
哈哈

pat和local是用户名称，可以随便取的，只要是字母即可，然后default节区里面的user指定使用哪一个

**Comment by luckypoem** [comment]
hi,
你说vssocks是reverse proxy, 不过reverse proxy不需要客户端的吧？
怎么你说“On the client's side, it provides a SOCKS5 server”呢？
还是vssocks可以用作一个普通的socks proxy?(带有服务器端和客户端的那种）

**Comment by hchen90** [comment]
代码和文档都有许多改动，有些不一致的内容被提交了

这个和jackpot是差不多的，只不过这个是把客户端的功能和服务端分开在两个程序里了
